RNA_COMBOS = {
    "aaa": "Lys",
    "aac": "Asn",
    "aag": "Lys",
    "aau": "Asn",
    "aca": "Thr",
    "acc": "Thr",
    "acg": "Thr",
    "acu": "Thr",
    "aga": "Arg",
    "agc": "Ser",
    "agg": "Arg",
    "agu": "Ser",
    "ucu": "Ser",
    "ucg": "Ser",
    "uca": "Ser",
    "ucc": "Ser",
    "aua": "Ile",
    "auc": "Ile",
    "aug": "Met",
    "auu": "Ile",
    "caa": "Gln",
    "cac": "His",
    "cag": "Gln",
    "cau": "His",
    "cca": "Pro",
    "ccc": "Pro",
    "ccg": "Pro",
    "ccu": "Pro",
    "cga": "Arg",
    "cgc": "Arg",
    "cgg": "Arg",
    "cgu": "Arg",
    "cua": "Leu",
    "cuc": "Leu",
    "cug": "Leu",
    "cuu": "Leu",
    "gaa": "Glu",
    "gac": "Asp",
    "gag": "Glu",
    "gau": "Asp",
    "gca": "Ala",
    "gcc": "Ala",
    "gcg": "Ala",
    "gcu": "Ala",
    "gga": "Gly",
    "ggc": "Gly",
    "ggg": "Gly",
    "ggu": "Gly",
    "gua": "Val",
    "guc": "Val",
    "gug": "Val",
    "guu": "Val",
    "uaa": "STOP",
    "uac": "Tyr",
    "uag": "STOP",
    "uau": "Tyr",
    "uga": "STOP",
    "ugc": "Cys",
    "ugg": "Trp",
    "ugu": "Cys",
    "uuc": "Phe",
    "uug": "Leu",
    "uuu": "Phe",
    "uua": "Leu",
}

STAGE_ONE_TRANSCRIPTION_MAP = {
    "c": "g",
    "t": "a",
    "a": "t",
    "g": "c",
}

STAGE_TWO_TRANSCRIPTION_MAP = {
    "c": "g",
    "t": "a",
    "a": "u",
    "g": "c",
}